application:
  bindAddress: :8445
  production: false
  debug: false
database:
  address: localhost:3401
  name: portfolio
  username: tradalia
  password: tradalia
authentication:
  authority: https://tradalia-server:8443/auth/realms/tradalia
  clientId: tradalia-backend
  clientSecret: YdImL2TpOb120tnerwsmLVJv6F3nHv0o
platform:
  storage: https://tradalia-server:8452/api/storage
  data   : https://tradalia-server:8446/api/collector
messaging:
  address: localhost:8450
  username: rabbit-admin
  password: rabbit.admin
